<?php
    $id = $this->getRequest()->getParam('id');
?>
<form class="" action="<?php echo $block->redirectBlogSave(); ?>" method="post">
    <input name="form_key" type="hidden" value="<?php echo $block->getFormKey();?>">    
    <div><a href="<?php echo $this->getBaseUrl()."post/blog/"; ?>"> Back</a></div><br>
    <fieldset class="fieldset">
        <legend class="legend"><span>Edit Form</span></legend><br>
        <div class="field title">
            <label class="label" for="title"><span>Name</span></label>
            <div class="control">
                <input name="id" type="hidden" value="<?php echo $id; ?>" class="input-text" type="text">
                <input name="name" id="title" title="Name" value="<?php echo $block->getPost($id)->getName(); ?>" class="input-text" type="text" required>
            </div>
        </div>
        <div class="field author">
            <label class="label" for="author"><span>Url Key</span></label>
            <div class="control">
                <input name="url" id="author" title="Url Key" value="<?php echo $block->getPost($id)->getUrlKey(); ?>" class="input-text" type="text" required>
            </div>
        </div>
        <div class="field author">
            <label class="label" for="author"><span>Tags</span></label>
            <div class="control">
                <input name="tags" id="author" title="Tags" value="<?php echo $block->getPost($id)->getTags(); ?>"  class="input-text" type="text" required>
            </div>
        </div>
        <div class="field content">
            <label class="label" for="content"><span>Content</span></label>
            <div class="control">
                <textarea name="content" id="content" title="Content" class="input-text" value="<?php echo $block->getPost($id)->getPostContent(); ?>" cols="5" rows="3"><?php echo $block->getPost($id)->getPostContent(); ?></textarea>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Submit" class="action submit primary">
                <span>Submit</span>
            </button>
        </div>
    </div>
</form>