<?php $post = $block->getPost($this->getRequest()->getParam('id')); ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>
<body>
    <div class="columns is-mobile">
        <div class="column">
            <div><a href="<?php echo $this->getBaseUrl()."post/blog/index"; ?>"> Back</a></div><br>
        </div>
        <div class="column">
            <span style="float:right;"><a href="<?php echo $block->getEditBlogUrl()."id/".$post->getPostId(); ?>"> Edit</a></span>
        </div>
    </div>
    <div class="columns is-mobile">
        <div class="column">
            <div>
                <h1 style="font-size:30px;"><?php echo $post->getName(); ?></h1>                
            </div>
            <br>
            <p><?php echo $post->getPostContent(); ?></p>
        </div>
        <div class="column">
            <img src="<?php echo $block->getBaseUrl()."pub/media/".$post->getFeaturedImage() ?>">
        </div>
    </div>
</body>
</html>

